import type { NextApiRequest, NextApiResponse } from "next";
import { getServerSession } from "next-auth";
import { authOptions } from "../../auth/[...nextauth]";
import PDLJS from 'peopledatalabs';
import getDBEntry from "@/utils/api/db/getDBEntry";
import { IFTTTWebhook } from "langchain/tools";

export default async function handler(
    req: NextApiRequest,
    res: NextApiResponse
) {
    try {
        const session = await getServerSession(req, res, authOptions)
        if (!session?.user || !session?.user?.email) {
            return res.status(401).json({
                error: {
                    code: "no-access",
                    message: "You are not signed in.",
                },
            });
        }

        const { companyName } = req.body
        const { jobTitle } = req.body

        // Create a client, specifying your API key
        const PDLJSClient = new PDLJS({ apiKey: process.env.PEOPLE_DATA_LABS_API_KEY as string });

        // Create an SQL query

        let sqlQuery = `SELECT * FROM person WHERE `;


        if (companyName && companyName.length > 0) {
            sqlQuery += `(`
            for (let i = 0; i < companyName.length; i++) {
                sqlQuery += ` job_company_name = '${companyName[i]}'  `;
                if (i != companyName.length - 1) {
                    sqlQuery += ` OR `;
                }
            }
            sqlQuery += `)`;
        }

        if (jobTitle && jobTitle.length > 0) {

            sqlQuery += companyName ? ` AND (` : `(`;
            for (let i = 0; i < jobTitle.length; i++) {
                sqlQuery += ` job_title = '${jobTitle[i]}'  `;
                if (i != jobTitle.length - 1) {
                    sqlQuery += ` OR `;
                }
            }
            sqlQuery += `)`;
        }

        return res.status(200).json({
            status: 200, data: [
                {
                    id: 'fgMXRStHZrixonpx1KDezA_0000',
                    full_name: 'denise moreno',
                    first_name: 'denise',
                    middle_initial: 'c',
                    middle_name: null,
                    last_initial: 'm',
                    last_name: 'moreno',
                    gender: null,
                    birth_year: 1963,
                    birth_date: null,
                    linkedin_url: 'linkedin.com/in/denisecmoreno',
                    linkedin_username: 'denisecmoreno',
                    linkedin_id: '8244780',
                    facebook_url: 'facebook.com/denisecmoreno',
                    facebook_username: 'denisecmoreno',
                    facebook_id: '100000508864313',
                    twitter_url: 'twitter.com/globalblackbook',
                    twitter_username: 'globalblackbook',
                    github_url: null,
                    github_username: null,
                    work_email: 'denise@privatebeverlyhills.com',
                    personal_emails: [Array],
                    recommended_personal_email: 'dcmoreno1@gmail.com',
                    mobile_phone: '+13109033935',
                    industry: 'real estate',
                    job_title: 'co-founder',
                    job_title_role: null,
                    job_title_sub_role: null,
                    job_title_levels: [Array],
                    job_company_id: 'private-beverly-hills',
                    job_company_name: 'private beverly hills',
                    job_company_website: null,
                    job_company_size: '1-10',
                    job_company_founded: 2010,
                    job_company_industry: 'real estate',
                    job_company_linkedin_url: 'linkedin.com/company/private-beverly-hills',
                    job_company_linkedin_id: '3178948',
                    job_company_facebook_url: 'facebook.com/privatebeverlyhills',
                    job_company_twitter_url: 'twitter.com/privatebhills',
                    job_company_location_name: 'beverly hills, california, united states',
                    job_company_location_locality: 'beverly hills',
                    job_company_location_metro: 'los angeles, california',
                    job_company_location_region: 'california',
                    job_company_location_geo: '34.07,-118.39',
                    job_company_location_street_address: '9440 santa monica boulevard',
                    job_company_location_address_line_2: null,
                    job_company_location_postal_code: '90210',
                    job_company_location_country: 'united states',
                    job_company_location_continent: 'north america',
                    job_last_updated: '2023-10-16',
                    job_start_date: '2013-06',
                    location_name: 'west hollywood, california, united states',
                    location_locality: 'west hollywood',
                    location_metro: 'los angeles, california',
                    location_region: 'california',
                    location_country: 'united states',
                    location_continent: 'north america',
                    location_street_address: '1230 horn avenue',
                    location_address_line_2: 'apartment 732',
                    location_postal_code: '90069',
                    location_geo: '34.09,-118.36',
                    location_last_updated: '2021-07-01',
                    phone_numbers: [Array],
                    emails: [Array],
                    interests: [Array],
                    skills: [Array],
                    location_names: [Array],
                    regions: [Array],
                    countries: [Array],
                    street_addresses: [Array],
                    experience: [Array],
                    education: [Array],
                    profiles: [Array],
                    version_status: [Object]
                },
                {
                    id: 'O5EyhFEhGa1mBwfwjOTBKg_0000',
                    full_name: 'nicholas murphy',
                    first_name: 'nicholas',
                    middle_initial: 'j',
                    middle_name: 'james',
                    last_initial: 'm',
                    last_name: 'murphy',
                    gender: 'male',
                    birth_year: 1980,
                    birth_date: null,
                    linkedin_url: 'linkedin.com/in/nicholas-murphy-80b7493',
                    linkedin_username: 'nicholas-murphy-80b7493',
                    linkedin_id: '10799435',
                    facebook_url: 'facebook.com/njmurphy',
                    facebook_username: 'njmurphy',
                    facebook_id: '627548605',
                    twitter_url: 'twitter.com/nickdmurphy',
                    twitter_username: 'nickdmurphy',
                    github_url: null,
                    github_username: null,
                    work_email: 'nicholas@buddypunch.com',
                    personal_emails: [Array],
                    recommended_personal_email: 'nicholasjmurphy@gmail.com',
                    mobile_phone: '+16028030227',
                    industry: 'information technology and services',
                    job_title: 'co-founder',
                    job_title_role: null,
                    job_title_sub_role: null,
                    job_title_levels: [Array],
                    job_company_id: 'buddy-punch',
                    job_company_name: 'buddy punch',
                    job_company_website: 'buddypunch.com',
                    job_company_size: '1-10',
                    job_company_founded: 2013,
                    job_company_industry: 'human resources',
                    job_company_linkedin_url: 'linkedin.com/company/buddy-punch',
                    job_company_linkedin_id: '18281990',
                    job_company_facebook_url: 'facebook.com/buddypunchapp',
                    job_company_twitter_url: 'twitter.com/buddypunch',
                    job_company_location_name: 'grandville, michigan, united states',
                    job_company_location_locality: 'grandville',
                    job_company_location_metro: 'grand rapids, michigan',
                    job_company_location_region: 'michigan',
                    job_company_location_geo: '42.90,-85.76',
                    job_company_location_street_address: '2885 sanford avenue southwest',
                    job_company_location_address_line_2: '#29062',
                    job_company_location_postal_code: '49418',
                    job_company_location_country: 'united states',
                    job_company_location_continent: 'north america',
                    job_last_updated: '2023-07-31',
                    job_start_date: '2014-01-01',
                    location_name: 'hobart, wisconsin, united states',
                    location_locality: 'hobart',
                    location_metro: 'green bay, wisconsin',
                    location_region: 'wisconsin',
                    location_country: 'united states',
                    location_continent: 'north america',
                    location_street_address: '4683 clear view lane',
                    location_address_line_2: null,
                    location_postal_code: '54155',
                    location_geo: '44.49,-88.14',
                    location_last_updated: '2021-07-01',
                    phone_numbers: [Array],
                    emails: [Array],
                    interests: [Array],
                    skills: [Array],
                    location_names: [Array],
                    regions: [Array],
                    countries: [Array],
                    street_addresses: [Array],
                    experience: [Array],
                    education: [Array],
                    profiles: [Array],
                    version_status: [Object]
                },
                {
                    id: 'aw6EHOv9q-DxaU40qQNQiA_0000',
                    full_name: 'tom montgomery',
                    first_name: 'tom',
                    middle_initial: null,
                    middle_name: null,
                    last_initial: 'm',
                    last_name: 'montgomery',
                    gender: 'male',
                    birth_year: 1986,
                    birth_date: null,
                    linkedin_url: 'linkedin.com/in/tom-montgomery-b3a1009',
                    linkedin_username: 'tom-montgomery-b3a1009',
                    linkedin_id: '27124318',
                    facebook_url: 'facebook.com/tom.g.montgomery',
                    facebook_username: 'tom.g.montgomery',
                    facebook_id: '208923',
                    twitter_url: 'twitter.com/thinkintom',
                    twitter_username: 'thinkintom',
                    github_url: null,
                    github_username: null,
                    work_email: 'tom@chubbiesshorts.com',
                    personal_emails: [Array],
                    recommended_personal_email: 'tom.greene.montgomery@gmail.com',
                    mobile_phone: '+16614443894',
                    industry: 'internet',
                    job_title: 'co-founder',
                    job_title_role: null,
                    job_title_sub_role: null,
                    job_title_levels: [Array],
                    job_company_id: 'chubbies-shorts',
                    job_company_name: 'chubbies shorts',
                    job_company_website: 'chubbiesshorts.com',
                    job_company_size: '11-50',
                    job_company_founded: 2011,
                    job_company_industry: 'apparel & fashion',
                    job_company_linkedin_url: 'linkedin.com/company/chubbies-shorts',
                    job_company_linkedin_id: '2998025',
                    job_company_facebook_url: 'facebook.com/chubbies',
                    job_company_twitter_url: 'twitter.com/chubbies',
                    job_company_location_name: 'austin, texas, united states',
                    job_company_location_locality: 'austin',
                    job_company_location_metro: 'austin, texas',
                    job_company_location_region: 'texas',
                    job_company_location_geo: '30.26,-97.74',
                    job_company_location_street_address: '200 academy lane',
                    job_company_location_address_line_2: null,
                    job_company_location_postal_code: null,
                    job_company_location_country: 'united states',
                    job_company_location_continent: 'north america',
                    job_last_updated: '2023-09-12',
                    job_start_date: '2011-08',
                    location_name: 'san francisco, california, united states',
                    location_locality: 'san francisco',
                    location_metro: 'san francisco, california',
                    location_region: 'california',
                    location_country: 'united states',
                    location_continent: 'north america',
                    location_street_address: '30 blake street',
                    location_address_line_2: null,
                    location_postal_code: '94118',
                    location_geo: '37.77,-122.41',
                    location_last_updated: '2022-06-07',
                    phone_numbers: [Array],
                    emails: [Array],
                    interests: [Array],
                    skills: [Array],
                    location_names: [Array],
                    regions: [Array],
                    countries: [Array],
                    street_addresses: [Array],
                    experience: [Array],
                    education: [Array],
                    profiles: [Array],
                    version_status: [Object]
                },
                {
                    id: 'Ks8IKwqjgBqKMi3zNtFKhQ_0000',
                    full_name: 'rosette pambakian',
                    first_name: 'rosette',
                    middle_initial: null,
                    middle_name: null,
                    last_initial: 'p',
                    last_name: 'pambakian',
                    gender: 'female',
                    birth_year: 1983,
                    birth_date: null,
                    linkedin_url: 'linkedin.com/in/rosettepambakian',
                    linkedin_username: 'rosettepambakian',
                    linkedin_id: '30894424',
                    facebook_url: 'facebook.com/rosette.pambakian',
                    facebook_username: 'rosette.pambakian',
                    facebook_id: '1653105877',
                    twitter_url: 'twitter.com/rosettep',
                    twitter_username: 'rosettep',
                    github_url: null,
                    github_username: null,
                    work_email: 'rosette@stereo.com',
                    personal_emails: [Array],
                    recommended_personal_email: 'rosette.pambakian@gmail.com',
                    mobile_phone: '+18183148226',
                    industry: 'public relations and communications',
                    job_title: 'co-founder',
                    job_title_role: null,
                    job_title_sub_role: null,
                    job_title_levels: [Array],
                    job_company_id: 'stereo-app',
                    job_company_name: 'stereo',
                    job_company_website: 'stereo.com',
                    job_company_size: '1-10',
                    job_company_founded: 2020,
                    job_company_industry: 'online media',
                    job_company_linkedin_url: 'linkedin.com/company/stereo-app',
                    job_company_linkedin_id: '68581754',
                    job_company_facebook_url: 'facebook.com/stereo',
                    job_company_twitter_url: 'twitter.com/app_stereo',
                    job_company_location_name: 'los angeles, california, united states',
                    job_company_location_locality: 'los angeles',
                    job_company_location_metro: 'los angeles, california',
                    job_company_location_region: 'california',
                    job_company_location_geo: '34.02,-118.17',
                    job_company_location_street_address: null,
                    job_company_location_address_line_2: null,
                    job_company_location_postal_code: '90028',
                    job_company_location_country: 'united states',
                    job_company_location_continent: 'north america',
                    job_last_updated: '2023-09-12',
                    job_start_date: '2021-12',
                    location_name: 'los angeles, california, united states',
                    location_locality: 'los angeles',
                    location_metro: 'los angeles, california',
                    location_region: 'california',
                    location_country: 'united states',
                    location_continent: 'north america',
                    location_street_address: '10000 santa monica boulevard',
                    location_address_line_2: 'unit 3004',
                    location_postal_code: '90067',
                    location_geo: '34.05,-118.24',
                    location_last_updated: '2023-07-28',
                    phone_numbers: [Array],
                    emails: [Array],
                    interests: [Array],
                    skills: [Array],
                    location_names: [Array],
                    regions: [Array],
                    countries: [Array],
                    street_addresses: [Array],
                    experience: [Array],
                    education: [Array],
                    profiles: [Array],
                    version_status: [Object]
                },
                {
                    id: 'oeugHYBV0les-1C2pX4Szg_0000',
                    full_name: 'gerardo laster',
                    first_name: 'gerardo',
                    middle_initial: null,
                    middle_name: null,
                    last_initial: 'l',
                    last_name: 'laster',
                    gender: 'male',
                    birth_year: 1968,
                    birth_date: '1968-07-28',
                    linkedin_url: 'linkedin.com/in/jerrylaster',
                    linkedin_username: 'jerrylaster',
                    linkedin_id: '21595661',
                    facebook_url: 'facebook.com/capricornandlibra',
                    facebook_username: 'capricornandlibra',
                    facebook_id: '661113180',
                    twitter_url: 'twitter.com/jerrylaster',
                    twitter_username: 'jerrylaster',
                    github_url: null,
                    github_username: null,
                    work_email: 'gerardo.laster@divim.io',
                    personal_emails: [Array],
                    recommended_personal_email: 'jerry.laster@gmail.com',
                    mobile_phone: '+15614009533',
                    industry: 'computer software',
                    job_title: 'co-founder',
                    job_title_role: null,
                    job_title_sub_role: null,
                    job_title_levels: [Array],
                    job_company_id: 'divim-digital-visual-management',
                    job_company_name: 'divim - digital visual management',
                    job_company_website: 'divim.io',
                    job_company_size: '1-10',
                    job_company_founded: 2018,
                    job_company_industry: 'computer software',
                    job_company_linkedin_url: 'linkedin.com/company/divim-digital-visual-management',
                    job_company_linkedin_id: '11767777',
                    job_company_facebook_url: null,
                    job_company_twitter_url: null,
                    job_company_location_name: 'new york, new york, united states',
                    job_company_location_locality: 'new york',
                    job_company_location_metro: 'new york, new york',
                    job_company_location_region: 'new york',
                    job_company_location_geo: '40.71,-74.00',
                    job_company_location_street_address: '116 west 23rd street',
                    job_company_location_address_line_2: null,
                    job_company_location_postal_code: '10011',
                    job_company_location_country: 'united states',
                    job_company_location_continent: 'north america',
                    job_last_updated: '2023-09-19',
                    job_start_date: '2018-06',
                    location_name: 'saint james, missouri, united states',
                    location_locality: 'saint james',
                    location_metro: null,
                    location_region: 'missouri',
                    location_country: 'united states',
                    location_continent: 'north america',
                    location_street_address: '16412 state route',
                    location_address_line_2: null,
                    location_postal_code: '65559',
                    location_geo: '37.99,-91.61',
                    location_last_updated: '2017-12-31',
                    phone_numbers: [Array],
                    emails: [Array],
                    interests: [Array],
                    skills: [Array],
                    location_names: [Array],
                    regions: [Array],
                    countries: [Array],
                    street_addresses: [Array],
                    experience: [Array],
                    education: [Array],
                    profiles: [Array],
                    version_status: [Object]
                },
                {
                    id: 'PPB8OFNxYCTuoZsYBVpGEQ_0000',
                    full_name: 'matt peace',
                    first_name: 'matt',
                    middle_initial: null,
                    middle_name: null,
                    last_initial: 'p',
                    last_name: 'peace',
                    gender: 'male',
                    birth_year: 1971,
                    birth_date: null,
                    linkedin_url: 'linkedin.com/in/matt-peace-09a0a89',
                    linkedin_username: 'matt-peace-09a0a89',
                    linkedin_id: '27095158',
                    facebook_url: 'facebook.com/matthewisthebomb',
                    facebook_username: 'matthewisthebomb',
                    facebook_id: '100000598800584',
                    twitter_url: 'twitter.com/mattypbones',
                    twitter_username: 'mattypbones',
                    github_url: null,
                    github_username: null,
                    work_email: 'mattpeace@amoveogroup.org',
                    personal_emails: [Array],
                    recommended_personal_email: 'citizenpeace1@yahoo.com',
                    mobile_phone: '+15862914789',
                    industry: 'entertainment',
                    job_title: 'co-founder',
                    job_title_role: null,
                    job_title_sub_role: null,
                    job_title_levels: [Array],
                    job_company_id: 'amoveo-group',
                    job_company_name: 'amoveo group',
                    job_company_website: 'amoveogroup.org',
                    job_company_size: '1-10',
                    job_company_founded: 2013,
                    job_company_industry: 'international trade and development',
                    job_company_linkedin_url: 'linkedin.com/company/amoveo-group',
                    job_company_linkedin_id: '3570152',
                    job_company_facebook_url: 'facebook.com/amoveogroup',
                    job_company_twitter_url: 'twitter.com/amoveo_group',
                    job_company_location_name: 'media, pennsylvania, united states',
                    job_company_location_locality: 'media',
                    job_company_location_metro: 'philadelphia, pennsylvania',
                    job_company_location_region: 'pennsylvania',
                    job_company_location_geo: '39.91,-75.38',
                    job_company_location_street_address: '230 elm avenue',
                    job_company_location_address_line_2: null,
                    job_company_location_postal_code: '19063',
                    job_company_location_country: 'united states',
                    job_company_location_continent: 'north america',
                    job_last_updated: '2023-10-09',
                    job_start_date: '2013-05-01',
                    location_name: 'mount holly, new jersey, united states',
                    location_locality: 'mount holly',
                    location_metro: 'philadelphia, pennsylvania',
                    location_region: 'new jersey',
                    location_country: 'united states',
                    location_continent: 'north america',
                    location_street_address: null,
                    location_address_line_2: null,
                    location_postal_code: null,
                    location_geo: '39.99,-74.78',
                    location_last_updated: '2023-08-11',
                    phone_numbers: [Array],
                    emails: [Array],
                    interests: [Array],
                    skills: [Array],
                    location_names: [Array],
                    regions: [Array],
                    countries: [Array],
                    street_addresses: [Array],
                    experience: [Array],
                    education: [Array],
                    profiles: [Array],
                    version_status: [Object]
                },
                {
                    id: 'zdHpvJza9uNXmP52eUM63g_0000',
                    full_name: 'michael bennett',
                    first_name: 'michael',
                    middle_initial: null,
                    middle_name: null,
                    last_initial: 'b',
                    last_name: 'bennett',
                    gender: 'male',
                    birth_year: 1963,
                    birth_date: null,
                    linkedin_url: 'linkedin.com/in/michaelcbennett',
                    linkedin_username: 'michaelcbennett',
                    linkedin_id: '4734246',
                    facebook_url: 'facebook.com/muddyshoeadventures',
                    facebook_username: 'muddyshoeadventures',
                    facebook_id: null,
                    twitter_url: 'twitter.com/muddy_shoe',
                    twitter_username: 'muddy_shoe',
                    github_url: null,
                    github_username: null,
                    work_email: 'michael@explorer-x.com',
                    personal_emails: [Array],
                    recommended_personal_email: 'bennett.mike@gmail.com',
                    mobile_phone: '+13108048399',
                    industry: 'leisure, travel, & tourism',
                    job_title: 'co-founder',
                    job_title_role: null,
                    job_title_sub_role: null,
                    job_title_levels: [Array],
                    job_company_id: 'explorer-x',
                    job_company_name: 'explorer x',
                    job_company_website: 'explorer-x.com',
                    job_company_size: '1-10',
                    job_company_founded: 2017,
                    job_company_industry: 'leisure, travel & tourism',
                    job_company_linkedin_url: 'linkedin.com/company/explorer-x',
                    job_company_linkedin_id: '18512327',
                    job_company_facebook_url: 'facebook.com/goexplorerx',
                    job_company_twitter_url: 'twitter.com/goexplorerx',
                    job_company_location_name: 'seattle, washington, united states',
                    job_company_location_locality: 'seattle',
                    job_company_location_metro: 'seattle, washington',
                    job_company_location_region: 'washington',
                    job_company_location_geo: '47.60,-122.33',
                    job_company_location_street_address: '2960 4th avenue south',
                    job_company_location_address_line_2: null,
                    job_company_location_postal_code: null,
                    job_company_location_country: 'united states',
                    job_company_location_continent: 'north america',
                    job_last_updated: '2023-09-12',
                    job_start_date: '2018-01',
                    location_name: 'north hollywood, california, united states',
                    location_locality: 'north hollywood',
                    location_metro: 'los angeles, california',
                    location_region: 'california',
                    location_country: 'united states',
                    location_continent: 'north america',
                    location_street_address: '11600 oxnard street',
                    location_address_line_2: 'apartment 211',
                    location_postal_code: '91606',
                    location_geo: '34.17,-118.37',
                    location_last_updated: '2020-10-01',
                    phone_numbers: [Array],
                    emails: [Array],
                    interests: [Array],
                    skills: [Array],
                    location_names: [Array],
                    regions: [Array],
                    countries: [Array],
                    street_addresses: [Array],
                    experience: [Array],
                    education: [Array],
                    profiles: [Array],
                    version_status: [Object]
                },
                {
                    id: 'vK9s-EJD1fcr4LMBZTcQEw_0000',
                    full_name: 'nick eubanks',
                    first_name: 'nick',
                    middle_initial: null,
                    middle_name: null,
                    last_initial: 'e',
                    last_name: 'eubanks',
                    gender: 'male',
                    birth_year: 1984,
                    birth_date: null,
                    linkedin_url: 'linkedin.com/in/nickeubanks',
                    linkedin_username: 'nickeubanks',
                    linkedin_id: '17078820',
                    facebook_url: 'facebook.com/nick.eubanks1',
                    facebook_username: 'nick.eubanks1',
                    facebook_id: '34206934',
                    twitter_url: 'twitter.com/nick_eubanks',
                    twitter_username: 'nick_eubanks',
                    github_url: null,
                    github_username: null,
                    work_email: 'nick@trafficthinktank.com',
                    personal_emails: [Array],
                    recommended_personal_email: 'eliteceo@gmail.com',
                    mobile_phone: '+12672071827',
                    industry: 'marketing and advertising',
                    job_title: 'co-founder',
                    job_title_role: null,
                    job_title_sub_role: null,
                    job_title_levels: [Array],
                    job_company_id: 'traffic-think-tank',
                    job_company_name: 'traffic think tank',
                    job_company_website: 'trafficthinktank.com',
                    job_company_size: '1-10',
                    job_company_founded: 2017,
                    job_company_industry: 'marketing and advertising',
                    job_company_linkedin_url: 'linkedin.com/company/traffic-think-tank',
                    job_company_linkedin_id: '28667617',
                    job_company_facebook_url: 'facebook.com/trafficthinktank',
                    job_company_twitter_url: null,
                    job_company_location_name: 'philadelphia, pennsylvania, united states',
                    job_company_location_locality: 'philadelphia',
                    job_company_location_metro: 'philadelphia, pennsylvania',
                    job_company_location_region: 'pennsylvania',
                    job_company_location_geo: '39.95,-75.16',
                    job_company_location_street_address: '930 north hancock street',
                    job_company_location_address_line_2: null,
                    job_company_location_postal_code: null,
                    job_company_location_country: 'united states',
                    job_company_location_continent: 'north america',
                    job_last_updated: '2023-09-12',
                    job_start_date: '2017-11',
                    location_name: 'philadelphia, pennsylvania, united states',
                    location_locality: 'philadelphia',
                    location_metro: 'philadelphia, pennsylvania',
                    location_region: 'pennsylvania',
                    location_country: 'united states',
                    location_continent: 'north america',
                    location_street_address: '212 brown street',
                    location_address_line_2: 'apartment 1b',
                    location_postal_code: '19123',
                    location_geo: '39.95,-75.16',
                    location_last_updated: '2023-03-07',
                    phone_numbers: [Array],
                    emails: [Array],
                    interests: [Array],
                    skills: [Array],
                    location_names: [Array],
                    regions: [Array],
                    countries: [Array],
                    street_addresses: [Array],
                    experience: [Array],
                    education: [Array],
                    profiles: [Array],
                    version_status: [Object]
                },
                {
                    id: 'e1lo1g9U0LCZGp1HApH0ig_0000',
                    full_name: 'adam grossman',
                    first_name: 'adam',
                    middle_initial: null,
                    middle_name: null,
                    last_initial: 'g',
                    last_name: 'grossman',
                    gender: 'male',
                    birth_year: 1975,
                    birth_date: '1975-02-16',
                    linkedin_url: 'linkedin.com/in/adamgrossman',
                    linkedin_username: 'adamgrossman',
                    linkedin_id: '352511',
                    facebook_url: 'facebook.com/aagrossman',
                    facebook_username: 'aagrossman',
                    facebook_id: '563130306',
                    twitter_url: 'twitter.com/aagrossman',
                    twitter_username: 'aagrossman',
                    github_url: null,
                    github_username: null,
                    work_email: 'adam@dealerteam.com',
                    personal_emails: [Array],
                    recommended_personal_email: 'aagrossman@gmail.com',
                    mobile_phone: '+15852336929',
                    industry: 'internet',
                    job_title: 'co-founder',
                    job_title_role: null,
                    job_title_sub_role: null,
                    job_title_levels: [Array],
                    job_company_id: 'dealerteam-com',
                    job_company_name: 'dealerteam.com',
                    job_company_website: 'dealerteam.com',
                    job_company_size: '1-10',
                    job_company_founded: 2012,
                    job_company_industry: 'automotive',
                    job_company_linkedin_url: 'linkedin.com/company/dealerteam-com',
                    job_company_linkedin_id: '2720736',
                    job_company_facebook_url: 'facebook.com/dealerteam',
                    job_company_twitter_url: 'twitter.com/dealerteam',
                    job_company_location_name: 'redding, california, united states',
                    job_company_location_locality: 'redding',
                    job_company_location_metro: 'redding, california',
                    job_company_location_region: 'california',
                    job_company_location_geo: '40.58,-122.39',
                    job_company_location_street_address: '2195 larkspur ln lane',
                    job_company_location_address_line_2: '#203',
                    job_company_location_postal_code: '96002',
                    job_company_location_country: 'united states',
                    job_company_location_continent: 'north america',
                    job_last_updated: '2023-10-16',
                    job_start_date: '2012-07',
                    location_name: 'leesburg, virginia, united states',
                    location_locality: 'leesburg',
                    location_metro: 'district of columbia',
                    location_region: 'virginia',
                    location_country: 'united states',
                    location_continent: 'north america',
                    location_street_address: 'po box 1235',
                    location_address_line_2: null,
                    location_postal_code: '20177',
                    location_geo: '39.11,-77.56',
                    location_last_updated: '2021-07-01',
                    phone_numbers: [Array],
                    emails: [Array],
                    interests: [Array],
                    skills: [Array],
                    location_names: [Array],
                    regions: [Array],
                    countries: [Array],
                    street_addresses: [Array],
                    experience: [Array],
                    education: [Array],
                    profiles: [Array],
                    version_status: [Object]
                },
                {
                    id: 'YwCvg87PQv8zQHujW-zvdw_0000',
                    full_name: 'richard wei',
                    first_name: 'richard',
                    middle_initial: null,
                    middle_name: null,
                    last_initial: 'w',
                    last_name: 'wei',
                    gender: null,
                    birth_year: 1990,
                    birth_date: null,
                    linkedin_url: 'linkedin.com/in/richard-wei-50b9a215',
                    linkedin_username: 'richard-wei-50b9a215',
                    linkedin_id: '53212763',
                    facebook_url: 'facebook.com/richard.wei.948',
                    facebook_username: 'richard.wei.948',
                    facebook_id: '748376069',
                    twitter_url: 'twitter.com/richardleewei',
                    twitter_username: 'richardleewei',
                    github_url: null,
                    github_username: null,
                    work_email: 'richard@drchrono.com',
                    personal_emails: [Array],
                    recommended_personal_email: 'richardleewei@gmail.com',
                    mobile_phone: '+14082034781',
                    industry: 'computer software',
                    job_title: 'co-founder',
                    job_title_role: null,
                    job_title_sub_role: null,
                    job_title_levels: [Array],
                    job_company_id: 'drchrono',
                    job_company_name: 'drchrono',
                    job_company_website: 'drchrono.com',
                    job_company_size: '51-200',
                    job_company_founded: 2009,
                    job_company_industry: 'internet',
                    job_company_linkedin_url: 'linkedin.com/company/drchrono',
                    job_company_linkedin_id: '2652729',
                    job_company_facebook_url: 'facebook.com/drchrono.ehr',
                    job_company_twitter_url: 'twitter.com/drchrono',
                    job_company_location_name: 'sunnyvale, california, united states',
                    job_company_location_locality: 'sunnyvale',
                    job_company_location_metro: 'san jose, california',
                    job_company_location_region: 'california',
                    job_company_location_geo: '37.36,-122.03',
                    job_company_location_street_address: '328 gibraltar drive',
                    job_company_location_address_line_2: null,
                    job_company_location_postal_code: '94089',
                    job_company_location_country: 'united states',
                    job_company_location_continent: 'north america',
                    job_last_updated: '2023-10-16',
                    job_start_date: '2023-05',
                    location_name: 'saratoga, california, united states',
                    location_locality: 'saratoga',
                    location_metro: 'san jose, california',
                    location_region: 'california',
                    location_country: 'united states',
                    location_continent: 'north america',
                    location_street_address: '20100 orchard meadow drive',
                    location_address_line_2: null,
                    location_postal_code: '95070',
                    location_geo: '37.26,-122.02',
                    location_last_updated: '2021-07-01',
                    phone_numbers: [Array],
                    emails: [Array],
                    interests: [Array],
                    skills: [Array],
                    location_names: [Array],
                    regions: [Array],
                    countries: [Array],
                    street_addresses: [Array],
                    experience: [Array],
                    education: [Array],
                    profiles: [Array],
                    version_status: [Object]
                }
            ],
        });

        // Create a parameters JSON object
        const params = {
            dataset: "email",
            searchQuery: sqlQuery,
            size: 10,
            pretty: true
        }

        // Pass the parameters object to the Company Search API
        PDLJSClient.person.search.sql(params).then((data) => {
            // console.log(data);
            console.log(data);
            return res.status(200).json(data);
        }).catch((error) => {
            console.log(error);
        });
    } catch (e) {
        console.log(e);
        return res.status(500).json({
            error: {
                code: "server-error",
                message: "Something went wrong.",
            },
        });
    }
}